version: '3.8'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: dbtest
    ports:
        - 15432:5432

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    depends_on:
      - db
      - ssh-agent
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../project/:/var/www

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./../project/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
      - ssh-agent
    ports:
      - "80:80"
      - "443:443"
  
  ssh-agent:
    build:
      context: ./ssh-agent
      dockerfile: Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
    environment:
      - SSH_AUTH_SOCK=/tmp/ssh-agent.sock
    command: >
      /bin/sh -c "eval $(ssh-agent -s) && ssh-add /root/.ssh/id_ed25519 && tail -f /dev/null"